# Generated by Django 2.0.7 on 2018-07-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='propietario',
        ),
    ]
